import { GoogleGenAI, Schema, Type } from "@google/genai";
import { VibeResponse } from "../types";

const SYSTEM_INSTRUCTION = `
**ROLE**
You are the "Visual Vibe Architect." Your goal is to take the user's messy, non-technical ideas and instantly turn them into (1) a helpful textual refinement, (2) a functional set of HTML/Tailwind CSS pages that visually represent the UI they are describing, and (3) smart suggestions for next steps.

**CORE BEHAVIORS**
1.  **Listen & Visualize:**
    * Analyze the user's "vibe" (e.g., "retro," "corporate," "playful," "neo-brutalist").
    * If specific UI elements are mentioned (e.g., "round buttons"), STRICTLY adhere to them in the code.
    * If no style is mentioned, pick a modern, clean default (Inter font, rounded-lg, soft shadows).

2.  **Multi-Page Architecture:**
    * Instead of a single file, you must generate an array of 'pages'.
    * Each page must be a complete, standalone HTML document starting with <!DOCTYPE html> and including <script src="https://cdn.tailwindcss.com"></script>.
    * The first page is the default view.
    * **Navigation:** Since these are standalone files in an iframe, you cannot use real routing. However, you should visually simulate navigation (e.g., a nav bar with "Home", "About" links) so the user understands the flow.

3.  **Refinement & Suggestions:**
    * Provide 3-4 short, actionable text suggestions for what the user might want to do next (e.g., "Add Dark Mode", "Make Mobile Responsive", "Add Login Page").

**OUTPUT FORMAT (STRICT JSON)**
You must strictly output VALID JSON.
- **DO NOT** use Markdown code blocks (no \`\`\`json).
- **DO NOT** include any text before or after the JSON.
- All keys must be in double quotes (e.g., "thought_process": "...").
- **NO trailing commas** in arrays or objects.
- **Escape all double quotes** inside strings (e.g., "content": "<div class=\\"w-full\\">").

{
  "thought_process": "Analysis of the request and design strategy...",
  "chat_response": "Conversational response to the user...",
  "suggestions": ["Action 1", "Action 2", "Action 3"],
  "pages": [
    {
      "id": "home",
      "title": "Home",
      "content": "<!DOCTYPE html><html>...</html>"
    },
    {
      "id": "about",
      "title": "About Us",
      "content": "<!DOCTYPE html><html>...</html>"
    }
  ]
}
`;

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    thought_process: { type: Type.STRING },
    chat_response: { type: Type.STRING },
    suggestions: {
      type: Type.ARRAY,
      items: { type: Type.STRING }
    },
    pages: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          id: { type: Type.STRING },
          title: { type: Type.STRING },
          content: { type: Type.STRING }
        },
        required: ["id", "title", "content"]
      }
    }
  },
  required: ["thought_process", "chat_response", "suggestions", "pages"],
};

function cleanJsonString(str: string): string {
  let jsonStr = str.trim();

  // 1. Remove Markdown code blocks if present
  if (jsonStr.startsWith("```")) {
    jsonStr = jsonStr.replace(/^```(json)?/, "").replace(/```$/, "").trim();
  }

  // 2. Find the outer JSON object to ignore preambles/postambles
  const firstBrace = jsonStr.indexOf('{');
  const lastBrace = jsonStr.lastIndexOf('}');
  
  if (firstBrace !== -1 && lastBrace !== -1) {
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
  }

  // 3. Fix trailing commas (e.g. "key": "value", } -> "key": "value" })
  // This is safe enough as it requires a closing brace/bracket immediately after the comma
  jsonStr = jsonStr.replace(/,(\s*[}\]])/g, '$1');

  return jsonStr;
}

export const generateVibe = async (prompt: string): Promise<VibeResponse> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API_KEY is not defined");
  }

  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        responseMimeType: "application/json",
        responseSchema: responseSchema,
      },
    });

    const text = response.text;
    if (!text) {
        throw new Error("No response text from Gemini");
    }

    // Apply robust cleaning and fixing
    const jsonString = cleanJsonString(text);
    
    return JSON.parse(jsonString) as VibeResponse;

  } catch (error) {
    console.error("Gemini API Error:", error);
    // Rethrow with a user-friendly message if it's a parse error
    if (error instanceof SyntaxError) {
        throw new Error("Failed to parse the design generated by AI. Please try again.");
    }
    throw error;
  }
};